module Vivarium
  VERSION: String

  class Error < ::StandardError
  end

  class Event < ::Struct
    attr_accessor pid: Integer?
    attr_accessor event_name: String?
    attr_accessor payload: String?

    def empty?: bool
    def self.from_binary: (String raw) -> Event
  end

  class MapStore
    def initialize: (?pin_dir: String pin_dir) -> void
    def register_pid: (Integer pid) -> untyped
    def unregister_pid: (Integer pid) -> untyped
    def drain_events: () -> Array[Event]
  end

  class Daemon
    BPF_PROGRAM_TEMPLATE: String
    def initialize: (?pin_dir: String pin_dir) -> void
    def run: () -> void
  end

  class ObservationSession
    def stop: () -> void
  end

  PIN_DIR: String
  CONFIG_ROOT_TARGETS_PIN: String
  CONFIG_SPAWNED_TARGETS_PIN: String
  CONFIG_TARGETS_PIN: String
  EVENT_INVOKED_PIN: String
  EVENT_WRITE_POS_PIN: String

  EVENT_NAME_SIZE: Integer
  EVENT_PAYLOAD_SIZE: Integer
  EVENT_STRUCT_SIZE: Integer
  EVENT_CAPACITY: Integer

  def self.observe: (?pin_dir: String pin_dir, ?logger: untyped logger, ?dest: untyped dest, ?format: Symbol format) { () -> untyped } -> untyped
  def self.top_observe: (?pin_dir: String pin_dir, ?logger: untyped logger, ?dest: untyped dest, ?format: Symbol format) -> ObservationSession
  def self.filter_internal_frames?: () -> bool
  def self.run_daemon!: (?Array[String] argv) -> void
end
